language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
before_script:
  - yarn
script:
  - yarn run test:cov
  - yarn run build
on:
  all_branches: true
after_success:
  - echo deploy
on:
  branch: master

