version: "3.7"

services:
  backend:
    build:
      context: .
      target: "develop"
    command: /bin/sh -c "yarn run start:dev"
    volumes:
      - .:/src
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      PORT: 3000
      MODE: DEV # Set to != DEV for production mode
      RUN_MIGRATIONS: "false"
    ports:
      - 8081:3000

  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

volumes:
  db-data:
