version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
      target: "develop"
    command: /bin/sh -c "yarn run start"
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    ports:
      - 8080:3000

  backend:
    build:
      context: ./backend
      target: "develop"
    command: /bin/sh -c " yarn run start:dev"
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    environment:
      DIAMONDS_ORM_HOST: database
      DIAMONDS_ORM_PORT: 5432
      DIAMONDS_ORM_USERNAME: postgres
      DIAMONDS_ORM_PASSWORD: postgres
      DIAMONDS_ORM_DATABASE: postgres
      PORT: 5000
    ports:
      - 8081:5000

  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

volumes:
  db-data:
