version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: .docker/dockerfiles/frontend
      target: "prod"
    ports:
      - 8080:8082

  backend:
    build:
      context: .
      dockerfile: .docker/dockerfiles/backend
      target: "prod"
    environment:
      - DATABASE_URL
      - SLACK_ACCESS_TOKEN
      - SLACK_SIGNING_SECRET
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
