version: "3.7"

networks:
  diamonds2:

services:
  base:
    image: diamonds2_base:latest
    build:
      context: .
      dockerfile: .docker/dockerfiles/base

  frontend:
    build:
      context: .
      dockerfile: .docker/dockerfiles/frontend
      target: develop
    environment:
      - VITE_API_BASE_URL=http://backend:3000/api
    volumes:
      - ./packages:/app/packages
    ports:
      - 8082:8082
    networks:
      - diamonds2
    depends_on:
      - base

  backend:
    build:
      context: .
      dockerfile: .docker/dockerfiles/backend
      target: develop
    volumes:
      - ./packages:/app/packages
      - ./packages/prisma:/app/prisma
    depends_on:
      - database
      - base
    environment:
      ENVIRONMENT: development
      DATABASE_URL: postgresql://diamonds:password@database:5433/diamonds?schema=public
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    networks:
      - diamonds2

  database:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: diamonds
      POSTGRES_USER: diamonds
      POSTGRES_PASSWORD: password
    command:
      - "-p 5433"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5433
    networks:
      - diamonds2

volumes:
  db-data:
  bot-data:
