version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
      target: "prod"
    command: /bin/sh -c "nginx -g 'daemon off;'"
    ports:
      - 8080:80

  backend:
    build:
      context: ./backend
      target: "prod"
    command: /bin/sh -c "yarn run typeorm:migration:run && yarn start:prod"
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PORT: 5000
      RUN_MIGRATIONS: "false"
    ports:
      - 8081:5000

  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data-db:/var/lib/postgresql/data

volumes:
  data-db:
