version: "3.7"

services:
  frontend:
    image: ghcr.io/etimo/diamonds2/frontend:${DIAMONDS_DOCKER_TAG}
    restart: always
    environment:
      - VITE_API_BASE_URL=http://backend:3000/api
      - PORT=8082
      - APP=frontend
    ports:
      - 80:8082
      - 443:443

    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot:latest
    restart: always
    entrypoint: "/bin/sh -c
      'trap exit TERM;
      while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  backend:
    image: ghcr.io/etimo/diamonds2/backend:${DIAMONDS_DOCKER_TAG}
    restart: always
    environment:
      - DATABASE_URL
      - SLACK_ACCESS_TOKEN
      - SLACK_SIGNING_SECRET
    ports:
      - 8081:3000
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
