version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
      target: "prod"
    command: /bin/sh -c "nginx -g 'daemon off;'"
    ports:
      - 8080:8082

  backend:
    build:
      context: ./backend
      target: "prod"
    command: /bin/sh -c "yarn run typeorm:migration:run && yarn start:prod"
    environment:
      - TYPEORM_HOST
      - TYPEORM_PORT
      - TYPEORM_DATABASE
      - TYPEORM_USERNAME
      - TYPEORM_PASSWORD
      - PORT=5000
      - SLACK_ACCESS_TOKEN
      - SLACK_SIGNING_SECRET
    ports:
      - 8081:5000
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"

  bots:
    build:
      context: ./example-bots/python
    restart: always
    volumes:
      - bot-data:/bot-data
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"

volumes:
  bot-data:
