version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
      target: "prod"
    command: /bin/sh -c "nginx -g 'daemon off;'"
    ports:
      - 8080:80

  backend:
    build:
      context: ./backend
      target: "develop"
    command: /bin/sh -c "yarn run start:dev"
    environment:
      - TYPEORM_HOST
      - TYPEORM_PORT
      - TYPEORM_DATABASE
      - TYPEORM_USERNAME
      - TYPEORM_PASSWORD
      - PORT=5000
    ports:
      - 8081:5000

  bots:
    build:
      context: ./example-bots/python
    restart: always
    volumes:
      - bot-data:/bot-data

volumes:
  bot-data: