version: "3.7"

services:
  frontend:
    image: etimodanielwinther/diamonds2_frontend:${DIAMONDS_DOCKER_TAG}
    command: /bin/sh -c "nginx -g 'daemon off;'"
    ports:
      - 80:80

  backend:
    image: etimodanielwinther/diamonds2_backend:${DIAMONDS_DOCKER_TAG}
    command: /bin/sh -c "yarn start:prod"
    environment:
      - DIAMONDS_ORM_HOST
      - DIAMONDS_ORM_PORT
      - DIAMONDS_ORM_DATABASE
      - DIAMONDS_ORM_USERNAME
      - DIAMONDS_ORM_PASSWORD
      - PORT=5000
      - RUN_MIGRATIONS=false
    ports:
      - 8081:5000
