version: "3.7"

services:
  backend:
    build:
      context: .
      target: "develop"
    command: /bin/sh -c "yarn run start:dev"
    volumes:
      - .:/src
    ports:
      - 8081:8080

  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

volumes:
  db-data:
