version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
      target: "develop"
    command: /bin/sh -c "yarn run start"
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 8080:3000

  backend:
    build:
      context: ./backend
      target: "develop"
    command: /bin/sh -c "yarn run start:dev"
    volumes:
      - ./backend/src:/app/src
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      PORT: 5000
      MODE: DEV # Set to != DEV for production mode
      RUN_MIGRATIONS: "false"
    ports:
      - 8081:5000

  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

volumes:
  db-data:
