name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  test-backend:
    name: Test backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node-using-nvm

      - name: Install dependencies
        run: yarn

      - name: Build
        run: npm run build

      - name: Run tests with coverage report
        run: yarn --cwd=packages/backend run test:coverage --forceExit

      - name: List coverage directory
        run: ls -la ./packages/backend
  # TODO: Add later (does not work atm)
  #      - name: Coveralls
  #        uses: coverallsapp/github-action@master
  #        with:
  #          github-token: ${{ secrets.GITHUB_TOKEN }}
  #          path-to-lcov: ./packages/backend/coverage/lcov.info

  # test-frontend:
  #   name: Test frontend
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '12.x'
  #     - name: Install dependencies
  #       run: yarn --cwd=frontend install
  # - name: Run tests
  #   run: yarn --cwd=frontend test

  # Test that building local dev env using docker works
  test-build:
    name: Build for dev env
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ref ${{ github.ref }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          docker build -t diamonds2_base:latest -f .docker/dockerfiles/base .
          docker compose -f docker-compose.yml build
