name: Build
on: [pull_request, push]
  # pull_request:
  #   branches:
  #     - master
  #     - develop
  # push:
  #   branches:
  #     - master
  #     - develop
jobs:
  test-backend:
    name: Test backend
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Change working dir
        run: cd backend
      - name: Install dependencies
        run: yarn install
      - name: Run tests with coverage report
        run: yarn test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test-frontend:
    name: Test frontend
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn --cwd=frontend install
      # - name: Run tests
      #   run: yarn --cwd=frontend test
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Build docker image
        run: docker-compose -f docker-compose.yml build

